(function(){
  "use strict";

  const profileImages={
    "Akane Owari":"https://static.wikia.nocookie.net/danganronpa/images/0/0e/Akane_Owari_Illustration.png/revision/latest?cb=20170530084146",
    "Angie Yonaga":"https://static.wikia.nocookie.net/danganronpa/images/d/d9/Angie_Yonaga_Illustration.png/revision/latest?cb=20170620185338",
    "Aoi Asahina":"https://static.wikia.nocookie.net/danganronpa/images/6/67/Aoi_Asahina_Illustration.png/revision/latest?cb=20210508173134",
    "Byakuya Togami":"https://static.wikia.nocookie.net/danganronpa/images/5/58/Byakuya_Togami_Illustration.png/revision/latest?cb=20170611004044",
    "Celestia Ludenberg":"https://static.wikia.nocookie.net/danganronpa/images/6/66/Celestia_Ludenberg_Illustration.png/revision/latest?cb=20250121230016",
    "Chiaki Nanami":"https://static.wikia.nocookie.net/danganronpa/images/a/a0/Chiaki_Nanami_Illustration.png/revision/latest?cb=20170706030737",
    "Chihiro Fujisaki":"https://static.wikia.nocookie.net/danganronpa/images/7/7e/Chihiro_Fujisaki_Illustration.png/revision/latest?cb=20170827162806",
    "Chisa Yukizome":"https://static.wikia.nocookie.net/danganronpa/images/e/e8/Danganronpa_3_-_Chisa_Yukizome_%28Future%29_Sidebar.png/revision/latest?cb=20200830144353",
    "Daisaku Bandai":"https://static.wikia.nocookie.net/danganronpa/images/9/9f/Danganronpa_3_-_Daisaku_Bandai_Sidebar.png/revision/latest?cb=20200830144355",
    "Fuyuhiko Kuzuryu":"https://static.wikia.nocookie.net/danganronpa/images/3/3f/Fuyuhiko_Kuzuryu_Illustration.png/revision/latest?cb=20170704214532",
    "Genocide Jill":"https://static.wikia.nocookie.net/danganronpa/images/4/4f/Genocide_Jack_Genocider_Syo_Illustration.png/revision/latest?cb=20170605013126",
    "Gonta Gokuhara":"https://static.wikia.nocookie.net/danganronpa/images/e/ed/Gonta_Gokuhara_Illustration.png/revision/latest?cb=20170620185536",
    "Great Gozu":"https://static.wikia.nocookie.net/danganronpa/images/8/8f/Danganronpa_3_-_Great_Gozu_Sidebar.png/revision/latest?cb=20200830144357",
    "Gundham Tanaka":"https://static.wikia.nocookie.net/danganronpa/images/8/84/Danganronpa_2_Character_Illustration_-_Gundham_Tanaka.png/revision/latest?cb=20250624113333",
    "Hajime Hinata":"https://static.wikia.nocookie.net/danganronpa/images/f/f3/Hajime_Hinata_Illustration.png/revision/latest?cb=20170608041605",
    "Hifumi Yamada":"https://static.wikia.nocookie.net/danganronpa/images/0/07/Hifumi_Yamada_Illustration.png/revision/latest?cb=20170605023117",
    "Himiko Yumeno":"https://static.wikia.nocookie.net/danganronpa/images/9/9d/Himiko_Yumeno_Illustration.png/revision/latest?cb=20170620185435",
    "Hiyoko Saionji":"https://static.wikia.nocookie.net/danganronpa/images/4/44/Hiyoko_Saionji_Illustration.png/revision/latest?cb=20170721042144",
    "Ibuki Mioda":"https://static.wikia.nocookie.net/danganronpa/images/6/6d/Ibuki_Mioda_Illustration.png/revision/latest?cb=20250121224700",
    "Junko Enoshima":"https://static.wikia.nocookie.net/danganronpa/images/5/5e/Junko_Enoshima_Illustration.png/revision/latest?cb=20250121230002",
    "Juzo Sakakura":"https://static.wikia.nocookie.net/danganronpa/images/7/72/Danganronpa_3_-_Juzo_Sakakura_%28Future%29_Sidebar.png/revision/latest?cb=20200830144401",
    "K1-B0":"https://static.wikia.nocookie.net/danganronpa/images/b/be/K1-B0_Illustration.png/revision/latest?cb=20180416200220",
    "Kaede Akamatsu":"https://static.wikia.nocookie.net/danganronpa/images/9/99/Kaede_Akamatsu_Illustration.png/revision/latest?cb=20170429155934",
    "Kaito Momota":"https://static.wikia.nocookie.net/danganronpa/images/8/8a/Kaito_Momota_Illustration.png/revision/latest?cb=20170620185637",
    "Kazuichi Soda":"https://static.wikia.nocookie.net/danganronpa/images/5/56/Kazuichi_Soda_Illustration.png/revision/latest?cb=20170724182621",
    "Kazuo Tengan":"https://static.wikia.nocookie.net/danganronpa/images/a/aa/Danganronpa_3_-_Kazuo_Tengan_%28Future%29_Sidebar.png/revision/latest?cb=20200830144405",
    "Kirumi Tojo":"https://static.wikia.nocookie.net/danganronpa/images/7/71/Kirumi_Tojo_Illustration.png/revision/latest?cb=20170620185620",
    "Kiyotaka Ishimaru":"https://static.wikia.nocookie.net/danganronpa/images/d/d6/Kiyotaka_Ishimaru_Illustration.png/revision/latest?cb=20170611020822",
    "Koichi Kizakura":"https://static.wikia.nocookie.net/danganronpa/images/f/f9/Danganronpa_3_-_Koichi_Kizakura_%28Future%29_Sidebar.png/revision/latest?cb=20200830144408",
    "Kokichi Oma":"https://static.wikia.nocookie.net/danganronpa/images/6/66/Kokichi_Oma_Ouma_Illustration.png/revision/latest?cb=20180925005631",
    "Komaru Naegi":"https://static.wikia.nocookie.net/danganronpa/images/d/d7/Komaru_Naegi_Illustration.png/revision/latest?cb=20211205215124",
    "Korekiyo Shinguji":"https://static.wikia.nocookie.net/danganronpa/images/3/3f/Korekiyo_Shinguji_Illustration.png/revision/latest?cb=20170620185357",
    "Kyoko Kirigiri":"https://static.wikia.nocookie.net/danganronpa/images/1/12/Kyoko_Kirigiri_Illustration.png/revision/latest?cb=20180925005620",
    "Kyosuke Munakata":"https://static.wikia.nocookie.net/danganronpa/images/0/0d/Danganronpa_3_-_Kyosuke_Munakata_%28Future%29_Sidebar.png/revision/latest?cb=20200830144413",
    "Leon Kuwata":"https://static.wikia.nocookie.net/danganronpa/images/4/4f/Leon_Kuwata_Illustration.png/revision/latest?cb=20210509213350",
    "Mahiru Koizumi":"https://static.wikia.nocookie.net/danganronpa/images/3/3f/Mahiru_Koizumi_Illustration.png/revision/latest?cb=20170608005250",
    "Maki Harukawa":"https://static.wikia.nocookie.net/danganronpa/images/1/1a/Maki_Harukawa_Illustration.png/revision/latest?cb=20170620185514",
    "Makoto Naegi":"https://static.wikia.nocookie.net/danganronpa/images/7/7c/Makoto_Naegi_Illustration.png/revision/latest?cb=20170510004857",
    "Miaya Gekkogahara":"https://static.wikia.nocookie.net/danganronpa/images/d/d9/Danganronpa_3_-_Miaya_Gekkogahara_Sidebar.png/revision/latest?cb=20200830144416",
    "Mikan Tsumiki":"https://static.wikia.nocookie.net/danganronpa/images/b/b0/Mikan_Tsumiki_Illustration.png/revision/latest?cb=20250121225641",
    "Miu Iruma":"https://static.wikia.nocookie.net/danganronpa/images/3/3b/Miu_Iruma_Illustration.png/revision/latest?cb=20250121224539",
    "Monaca Towa":"https://static.wikia.nocookie.net/danganronpa/images/c/c5/Monaca_Towa_Illustration.png/revision/latest?cb=20211205225543",
    "Mondo Owada":"https://static.wikia.nocookie.net/danganronpa/images/d/d1/Mondo_Owada_Illustration.png/revision/latest?cb=20210508214924",
    "Monodam":"https://static.wikia.nocookie.net/danganronpa/images/e/e2/Monodam_Illustration.png/revision/latest?cb=20170620190437",
    "Monokid":"https://static.wikia.nocookie.net/danganronpa/images/a/ab/Monokid_Illustration.png/revision/latest?cb=20170620190402",
    "Monokuma":"https://static.wikia.nocookie.net/danganronpa/images/b/b4/Monokuma_Illustration.png/revision/latest?cb=20170716023807",
    "Monomi":"https://static.wikia.nocookie.net/danganronpa/images/2/24/Danganronpa_S_Monomi_Illustration.png/revision/latest?cb=20211205221218",
    "Monophanie":"https://static.wikia.nocookie.net/danganronpa/images/e/ee/Monophanie_Illustration.png/revision/latest?cb=20170620190333",
    "Monosuke":"https://static.wikia.nocookie.net/danganronpa/images/f/f5/Monosuke_Illustration.png/revision/latest?cb=20170620185801",
    "Monotaro":"https://static.wikia.nocookie.net/danganronpa/images/3/34/Monotarou_Monotaro_Illustration.png/revision/latest?cb=20170620185743",
    "Mukuro Ikusaba":"https://static.wikia.nocookie.net/danganronpa/images/0/06/Mukuro_Ikusaba_Illustration.png/revision/latest?cb=20210508221203",
    "Nagito Komaeda":"https://static.wikia.nocookie.net/danganronpa/images/7/7d/Nagito_Komaeda_Illustration.png/revision/latest?cb=20180925005643",
    "Nekomaru Nidai":"https://static.wikia.nocookie.net/danganronpa/images/8/85/Nekomaru_Nidai_Illustration.png/revision/latest?cb=20170804034803",
    "Peko Pekoyama":"https://static.wikia.nocookie.net/danganronpa/images/a/ab/Peko_Pekoyama_Illustration.png/revision/latest?cb=20170907184747",
    "Rantaro Amami":"https://static.wikia.nocookie.net/danganronpa/images/b/b3/Rantarou_Rantaro_Amami_Illustration.png/revision/latest?cb=20170425143131",
    "Ruruka Ando":"https://static.wikia.nocookie.net/danganronpa/images/6/67/Danganronpa_3_-_Ruruka_Ando_%28Future%29_Sidebar.png/revision/latest?cb=20200830144418",
    "Ryoma Hoshi":"https://static.wikia.nocookie.net/danganronpa/images/a/ae/Ryoma_Hoshi_Illustration.png/revision/latest?cb=20170620185715",
    "Ryota Mitarai":"https://static.wikia.nocookie.net/danganronpa/images/2/28/Danganronpa_3_-_Ryota_Mitarai_%28Future%29_Sidebar.png/revision/latest?cb=20200830144420",
    "Sakura Ogami":"https://static.wikia.nocookie.net/danganronpa/images/7/73/Sakura_Ogami_Transparent_Illustration.png/revision/latest?cb=20201223024049",
    "Sayaka Maizono":"https://static.wikia.nocookie.net/danganronpa/images/b/ba/Sayaka_Maizono_Illustration.png/revision/latest?cb=20240323155258",
    "Seiko Kimura":"https://static.wikia.nocookie.net/danganronpa/images/7/75/Danganronpa_3_-_Seiko_Kimura_%28Future%29_Sidebar.png/revision/latest?cb=20200830144424",
    "Shuichi Saihara":"https://static.wikia.nocookie.net/danganronpa/images/6/6c/Shuuichi_Shuichi_Saihara_Illustration.png/revision/latest?cb=20180416195826",
    "Sonia Nevermind":"https://static.wikia.nocookie.net/danganronpa/images/5/57/Sonia_Nevermind_Illustration.png/revision/latest?cb=20170708223405",
    "Sonosuke Izayoi":"https://static.wikia.nocookie.net/danganronpa/images/b/b4/Danganronpa_3_-_Sonosuke_Izayoi_%28Future%29_Sidebar.png/revision/latest?cb=20200830144427",
    "Tenko Chabashira":"https://static.wikia.nocookie.net/danganronpa/images/f/fc/Tenko_Chabashira_Illustration.png/revision/latest?cb=20170620185558",
    "Teruteru Hanamura":"https://static.wikia.nocookie.net/danganronpa/images/2/27/Teruteru_Hanamura_Illustration.png/revision/latest?cb=20170705010003",
    "Toko Fukawa":"https://static.wikia.nocookie.net/danganronpa/images/d/d4/Toko_Fukawa_Illustration.png/revision/latest?cb=20170524232846",
    "Tsumugi Shirogane":"https://static.wikia.nocookie.net/danganronpa/images/0/0b/Tsumugi_Shirogane_Illustration.png/revision/latest?cb=20250121225439",
    "Yasuhiro Hagakure":"https://static.wikia.nocookie.net/danganronpa/images/1/19/Yasuhiro_Hagakure_Illustration.png/revision/latest?cb=20250114211952"
  };

  const profileOverrides={
    dr1:{
      "Monokuma":"assets/monopad/dr1/monokuma.png",
      "Makoto Naegi":"assets/monopad/dr1/makoto-naegi.png",
      "Aoi Asahina":"assets/monopad/dr1/aoi-asahina.png",
      "Byakuya Togami":"assets/monopad/dr1/byakuya-togami.png",
      "Celestia Ludenberg":"assets/monopad/dr1/celestia-ludenberg.jpeg",
      "Chihiro Fujisaki":"assets/monopad/dr1/chihiro-fujisaki.png",
      "Hifumi Yamada":"assets/monopad/dr1/hifumi-yamada.png",
      "Junko Enoshima":"assets/monopad/dr1/junko-disguise.png",
      "Kiyotaka Ishimaru":"assets/monopad/dr1/kiyotaka-ishimaru.png",
      "Kyoko Kirigiri":"assets/monopad/dr1/kyoko-kirigiri.png",
      "Leon Kuwata":"assets/monopad/dr1/leon-kuwata.webp",
      "Mondo Owada":"assets/monopad/dr1/mondo-owada.png",
      "Sakura Ogami":"assets/monopad/dr1/sakura-ogami.jpg",
      "Sayaka Maizono":"assets/monopad/dr1/sayaka-maizono.jpg",
      "Toko Fukawa":"assets/monopad/dr1/toko-fukawa.jpg",
      "Yasuhiro Hagakure":"assets/monopad/dr1/yasuhiro-hagakure.png",
      "Genocide Jill":"assets/monopad/dr1/genocide-jill.jpg"
    }
  };

  const bios={
    dr1:{
      "Monokuma":"A talking black-and-white bear who claims to be Hope's Peak's headmaster. He is cheerful about the killing-game rules, enjoys bad jokes, and always seems happiest when everyone else is uncomfortable.",
      "Makoto Naegi":"A completely average student who got into Hope's Peak through the school's lottery. He calls himself ordinary, but he is friendly, level-headed, and tries to keep going even when he is scared.",
      "Aoi Asahina":"The Ultimate Swimming Pro, though she would rather everyone call her Hina. She is upbeat, straightforward, and seems to have almost as much energy for doughnuts as she does for sports.",
      "Byakuya Togami":"The heir to the enormous Togami family fortune. He is intelligent, cold, and makes it very clear from the first conversation that he considers most people beneath him.",
      "Celestia Ludenberg":"A mysterious gambler dressed like a gothic doll. She speaks very politely, keeps an excellent poker face, and claims she has never lost a bet.",
      "Chihiro Fujisaki":"A small, soft-spoken programmer who seems nervous around new people. Chihiro apologizes a lot, but is kind and already famous for creating useful software.",
      "Hifumi Yamada":"The Ultimate Fanfic Creator, best known for selling an enormous number of copies at a school festival. He talks at length, takes his interests very seriously, and strongly prefers the 2D world.",
      "Junko Enoshima":"The Ultimate Fashionista, recognizable from magazines even though she looks a little different in person. She is casual, confident, and much easier to talk to than her celebrity image suggests.",
      "Kiyotaka Ishimaru":"A painfully serious student who introduces himself at full volume. Taka believes in rules, effort, and proper conduct, and seems ready to turn every conversation into a disciplinary meeting.",
      "Kyoko Kirigiri":"A quiet girl whose Ultimate talent is unknown. She says very little about herself, stays calm, and gives the impression that she notices much more than she explains.",
      "Leon Kuwata":"The Ultimate Baseball Star, despite barely practicing and not wanting a baseball career. Leon would rather become a musician and is already trying to leave his old image behind.",
      "Mondo Owada":"The leader of Japan's largest biker gang. He has a very short temper and looks ready to start a fight, but takes pride in strength, courage, and keeping his word.",
      "Sakura Ogami":"The Ultimate Martial Artist, famous enough to be called the strongest human alive. She looks terrifying at first, but speaks calmly and carries herself with surprising patience.",
      "Sayaka Maizono":"The center of a hugely popular idol group and someone Makoto recognizes from middle school. She is warm, observant, and quick to make him feel less alone among all the Ultimates.",
      "Toko Fukawa":"A bestselling romance novelist who won awards while still in school. Toko is tense, suspicious, and so quick to assume she is being insulted that an ordinary introduction becomes difficult.",
      "Yasuhiro Hagakure":"The Ultimate Clairvoyant—Hiro for short—who claims his predictions are right thirty percent of the time. He has been held back more than once, talks casually, and is completely serious about crystal balls and the occult.",
      "Genocide Jill":"Toko's other personality and the serial killer everyone has heard about. Jill is loud, vulgar, obsessed with handsome men, and delighted to explain exactly how different she is from Toko.",
      "Mukuro Ikusaba":"The mysterious sixteenth student and the Ultimate Soldier. She is a highly trained fighter connected to the mercenary group Fenrir, but reveals very little about what she actually wants.",
      "Junko Enoshima (Real)":"The real Ultimate Fashionista and the person behind the killing game. She changes moods and mannerisms constantly, as though sticking to one personality would bore her."
    },
    dr2:{
      "Hajime Hinata":"A practical student who cannot remember what Ultimate talent brought him to Hope's Peak. Hajime questions strange claims, grounds the group in common sense, and is determined to recover the missing part of his identity.",
      "Nagito Komaeda":"The polite Ultimate Lucky Student has a gentle manner and an intense fascination with hope. His improbable luck and unusual way of judging people make him difficult to read.",
      "Gundham Tanaka":"The theatrical Ultimate Breeder calls himself a dark overlord and his four hamsters the Dark Devas of Destruction. Beneath the grand speeches, Gundham understands animals exceptionally well and takes their care seriously.",
      "Kazuichi Soda":"The Ultimate Mechanic is expressive, anxious, and able to take machines apart almost on instinct. Kazuichi is sociable when relaxed, though fear and infatuation can send his imagination racing.",
      "Byakuya Togami":"The imposing Ultimate Affluent Progeny immediately assumes a leadership role. Direct, confident, and highly organized, he focuses on practical control of the group's dangerous situation.",
      "Teruteru Hanamura":"The Ultimate Cook is proud of his sophisticated food and his family's humble diner. Teruteru is hospitable and talented in the kitchen, though his attempts at flirtation routinely cross the line.",
      "Nekomaru Nidai":"The booming Ultimate Team Manager approaches every problem like an athlete who needs one more push. Nekomaru is physically imposing, relentlessly encouraging, and genuinely invested in helping others reach their potential.",
      "Fuyuhiko Kuzuryu":"The young Ultimate Yakuza compensates for his small stature with aggression and distance. Fuyuhiko rejects easy friendship and insists he can survive alone, but takes status and obligation very seriously.",
      "Akane Owari":"The instinctive Ultimate Gymnast loves food, fighting, and any challenge that lets her move. Akane is fearless and direct, relying more on sharp senses and physical reactions than careful planning.",
      "Chiaki Nanami":"The sleepy Ultimate Gamer compares unfamiliar problems to game mechanics. Chiaki is quiet and sometimes slow to react socially, but becomes focused, patient, and perceptive when the group needs a solution.",
      "Sonia Nevermind":"The Ultimate Princess is a foreign royal with impeccable manners and enthusiastic curiosity about Japanese culture. Sonia is diplomatic and well educated, but her interests can take surprisingly macabre turns.",
      "Hiyoko Saionji":"The tiny Ultimate Traditional Dancer comes from a celebrated performance family. Hiyoko presents an adorable image while delivering merciless insults, especially when she senses vulnerability.",
      "Mahiru Koizumi":"The dependable Ultimate Photographer specializes in portraits and candid everyday moments. Mahiru is practical, outspoken about responsibility, and often tries to make the group behave like capable adults.",
      "Mikan Tsumiki":"The Ultimate Nurse is timid, apologetic, and used to being treated poorly. Her medical knowledge is extensive, and caring for an injured person gives her a confidence she rarely shows otherwise.",
      "Ibuki Mioda":"The Ultimate Musician is loud, imaginative, and committed to making every moment more energetic. Ibuki follows her curiosity without embarrassment and treats new friends like an instant audience and band.",
      "Peko Pekoyama":"The composed Ultimate Swordswoman is formal, vigilant, and rarely separated from her bamboo sword. Peko speaks precisely and tends to define herself through usefulness rather than personal wants.",
      "Monokuma":"The returning black-and-white headmaster takes control of Jabberwock Island with threats, motives, and class trials. He delights in breaking peaceful routines and turning confusion into spectacle.",
      "Monomi":"A pink rabbit teacher who wants the island trip to remain peaceful and cooperative. Monomi is earnest, easily bullied by Monokuma, and keeps trying to protect the students even when they distrust her."
    },
    dr3anime:{
      "Kazuo Tengan":"The elderly chairman of the Future Foundation is calm, experienced, and responsible for balancing its competing branches. He prefers deliberation, even as younger leaders demand harsher action.",
      "Kyosuke Munakata":"The Future Foundation vice chairman is an uncompromising leader who believes despair must be destroyed decisively. His discipline and certainty inspire loyalty, but leave little room for doubt or mercy.",
      "Koichi Kizakura":"A relaxed former Hope's Peak scout and teacher whose casual habits hide sharp observation. Kizakura knows many of the academy's graduates and watches tense situations more carefully than he lets on.",
      "Seiko Kimura":"The Ultimate Pharmacist is a brilliant, withdrawn researcher able to produce medicines for almost any need. She is uncomfortable in groups and carries the scars of a painful breakdown in trust.",
      "Chisa Yukizome":"The Ultimate Housekeeper is an energetic former teacher with close ties to Hope's Peak and the Future Foundation. Chisa meets hardship with warmth, determination, and an almost impossible level of enthusiasm.",
      "Juzo Sakakura":"The Ultimate Boxer serves as Munakata's forceful security chief. Juzo is proud, confrontational, and fiercely loyal, usually choosing direct action over patient explanation.",
      "Miaya Gekkogahara":"The Ultimate Therapist communicates through a small avatar displayed on her wheelchair. Her calm professional presence is intended to lower tension among people who are already close to breaking.",
      "Ruruka Ando":"The Ultimate Confectioner is charming, demanding, and proud of sweets that can win people over. She values loyalty intensely and reacts badly when affection or trust is not returned in the form she expects.",
      "Sonosuke Izayoi":"The quiet Ultimate Blacksmith is a skilled weapon maker and Ruruka's devoted partner. He speaks little, remains alert to physical danger, and communicates most clearly through unwavering loyalty.",
      "Ryota Mitarai":"The Ultimate Animator is a nervous creative prodigy who believes animation can move anyone's heart. He works obsessively, avoids confrontation, and places enormous faith in the emotional power of images.",
      "Daisaku Bandai":"The Ultimate Farmer is a huge man with a gentle voice and a patient temperament. He tries to defuse conflict and prefers cooperation over the aggressive politics surrounding him.",
      "Great Gozu":"The masked Ultimate Wrestler combines tremendous strength with courtesy and a protective sense of fair play. He is one of the first leaders willing to defend Makoto long enough to hear him out.",
      "Aoi Asahina":"Now working with the Future Foundation, Aoi remains energetic, emotionally direct, and fiercely loyal to Makoto and Kyoko. She responds to danger quickly and refuses to abandon her friends.",
      "Kyoko Kirigiri":"The reserved detective works with the Future Foundation while continuing to notice patterns others miss. Kyoko stays composed under pressure and tests evidence before committing to an explanation.",
      "Makoto Naegi":"Known as the Ultimate Hope, Makoto still relies on empathy rather than authority. He believes even people consumed by despair may be saved, a position that places him at odds with more ruthless Foundation leaders.",
      "Yasuhiro Hagakure":"Hiro remains a superstitious clairvoyant with a talent for surviving trouble at the edge of the action. His strange conclusions rarely sound reassuring, even when his instincts point in a useful direction.",
      "Monokuma":"The familiar robotic bear returns as the smiling announcer of another deadly game. He explains new rules with deliberate ambiguity and uses every broadcast to increase suspicion.",
      "Byakuya Togami":"Byakuya supports the Future Foundation with the confidence and resources of the Togami heir. He is brisk, demanding, and focused on solving practical threats rather than comforting anyone.",
      "Komaru Naegi":"Makoto's younger sister survived the crisis in Towa City and learned to act despite feeling ordinary. Komaru is empathetic, expressive, and more resilient than she tends to give herself credit for.",
      "Toko Fukawa":"The Ultimate Writing Prodigy has become Komaru's sharp-tongued, fiercely protective companion. Toko remains defensive and dramatic, but now has someone she is willing to risk herself for.",
      "Monaca Towa":"The young Towa Group heir is intelligent, theatrical, and skilled at presenting herself as harmless. She understands how to press emotional weaknesses and prefers controlling events from a safe distance."
    },
    v3:{
      "Kaede Akamatsu":"The Ultimate Pianist is upbeat, proactive, and quick to turn a frightened group toward a shared plan. Kaede speaks plainly, dislikes surrender, and uses musical metaphors when encouraging others.",
      "Shuichi Saihara":"The Ultimate Detective is observant but uneasy about the consequences of exposing the truth. Shuichi is thoughtful, cautious, and more capable than his lack of confidence initially suggests.",
      "Rantaro Amami":"A relaxed, worldly student whose Ultimate talent is unknown even to him. Rantaro asks careful questions, keeps his own counsel, and seems less surprised by the academy than most of the group.",
      "Miu Iruma":"The Ultimate Inventor is a prolific engineer with a loud, vulgar, and aggressively confident persona. Miu can produce remarkable devices quickly, though her bravado collapses when someone pushes back.",
      "Kokichi Oma":"The self-declared Ultimate Supreme Leader says he commands a vast secret organization. Kokichi lies as naturally as he breathes, turning every conversation into a test of what others are willing to believe.",
      "K1-B0":"The earnest Ultimate Robot, usually called Keebo, wants to be treated as a person rather than a machine. He is polite, proud of his advanced functions, and extremely sensitive to anything he considers robophobic.",
      "Gonta Gokuhara":"The Ultimate Entomologist is a powerful but gentle student determined to become a true gentleman. Gonta loves insects, takes promises literally, and assumes other people are speaking honestly.",
      "Tsumugi Shirogane":"The Ultimate Cosplayer is a self-described plain girl who becomes animated when discussing costumes and fiction. Tsumugi is observant, friendly, and fond of references that not everyone recognizes.",
      "Korekiyo Shinguji":"The Ultimate Anthropologist studies customs, folklore, and the many forms of human behavior. Korekiyo is formal, unsettlingly calm, and genuinely fascinated by how extreme circumstances reveal people.",
      "Tenko Chabashira":"The Ultimate Aikido Master practices a style she calls Neo-Aikido. Tenko is energetic, emotionally transparent, fiercely supportive of other girls, and immediately suspicious of nearly every boy.",
      "Kirumi Tojo":"The Ultimate Maid is composed, efficient, and committed to fulfilling any reasonable request. Kirumi naturally becomes the group's organizer because she treats service as a serious responsibility rather than a lowly role.",
      "Maki Harukawa":"The Ultimate Child Caregiver is quiet, blunt, and uncomfortable with attempts to know her better. Maki prefers solitude and reacts to forced friendliness with a stare sharp enough to end most conversations.",
      "Ryoma Hoshi":"The Ultimate Tennis Pro is a small, world-weary former star with extraordinary skill and little attachment to his own future. Ryoma is perceptive, mature, and speaks as though his best days are already behind him.",
      "Kaito Momota":"The Ultimate Astronaut is bold, emotional, and determined to act like everyone's dependable older brother. Kaito backs people before the evidence does and believes confidence can be trained through action.",
      "Himiko Yumeno":"The Ultimate Magician insists her stagecraft is real magic and dismisses effort as a drain on her mana. Himiko is sleepy and reserved, but stubbornly committed to maintaining her mystical persona.",
      "Angie Yonaga":"The Ultimate Artist is a cheerful sculptor who says her inspiration comes directly from Atua. Angie is persuasive, untroubled by the academy's strangeness, and certain that faith can tell the group what to do.",
      "Monokuma":"The robotic headmaster oversees the Ultimate Academy and its newest killing game. His familiar jokes, motives, and punishments are now accompanied by a noisy family of smaller bears.",
      "Monokid":"A loud, aggressive Monokub who favors rock-star posing and reckless destruction. Monokid talks over the others and treats violence like part of the show.",
      "Monotaro":"The red Monokub attempts to lead his siblings despite being forgetful and easily distracted. He swings between bossy declarations and complete confusion.",
      "Monosuke":"The yellow Monokub is cynical, talkative, and fixated on money and status. He frequently comments from the sidelines as though the killing game were a business venture.",
      "Monophanie":"The pink Monokub affects a gentler manner and recoils from the group's uglier behavior. Her sweetness is inconsistent, especially when the siblings compete for Monokuma's approval.",
      "Monodam":"The green, quiet Monokub speaks in a mechanical monotone and wants his siblings to cooperate. Being ignored or mistreated only makes his calls for unity more ominous."
    }
  };

  const recaps={
    dr1:[
      {pretrial:"The students learned that Hope's Peak had become a sealed prison and that escape required murdering a classmate without being identified. Motive videos placed their loved ones in danger. Sayaka arranged to switch rooms with Makoto, and she was later found dead in his bathroom, forcing the class to investigate the first murder.",full:"The first Class Trial reconstructed Sayaka's failed attempt to frame Makoto. Leon had turned her own weapon against her, destroyed evidence in the incinerator, and left behind a dying message that pointed to him. The class voted correctly, and Monokuma executed Leon while making the cost of every future mistake unmistakable."},
      {pretrial:"Monokuma threatened to expose everyone's secrets. After Chihiro was found in the girls' locker room, evidence involving the switching room posters, a missing extension cord, and the serial killer Genocide Jill made the crime look deliberately confusing. The investigation also exposed that the locker-room access rules were central to the setup.",full:"The Trial revealed that Mondo killed Chihiro after Chihiro asked him for help becoming stronger. Mondo moved the body and altered the scene to protect Chihiro's secret, while Byakuya later changed it again to test the group. Mondo was executed, Taka was devastated, and Chihiro's laptop program Alter Ego became a new source of help."},
      {pretrial:"Alter Ego began analyzing the school's files while Monokuma offered ten million dollars as a motive. A staged sequence of attacks involving Robo Justice ended with both Taka and Hifumi dead, Celeste apparently abducted, and the bodies moving between rooms. Conflicting eyewitness accounts made the order of events the key mystery.",full:"Celeste had manipulated Hifumi into killing Taka, then killed Hifumi and used the Robo Justice costume and false sightings to disguise the timeline. Hifumi's final words and Celeste's slips exposed the plan. After her execution, the group learned where she had hidden Alter Ego, only to discover that Monokuma had already taken it."},
      {pretrial:"Sakura confessed that Monokuma had forced her to act as the school's spy, fracturing the group's trust even after she rejected him. She invited several classmates to the recreation room and was later found dead inside the locked room after being struck and poisoned. Aoi's anger and a damaged suicide note pushed suspicion in several directions.",full:"Sakura had taken her own life to end the conflict and protect the others. Aoi hid the truth and deliberately led the class toward a wrong vote because she blamed everyone for Sakura's despair, while Monokuma replaced part of Sakura's note to deepen that anger. Sakura's real message reunited the survivors, and Alter Ego made one final act of resistance before being destroyed."},
      {pretrial:"Kyoko's investigations opened new areas of the school while her absence created tension with Makoto. A masked body was discovered in the garden and then destroyed by an explosion, leaving only limited physical evidence and clues identifying the victim as Mukuro Ikusaba, the mysterious sixteenth student.",full:"Monokuma rushed an incomplete Trial designed to condemn either Kyoko or Makoto. Makoto refused to expose Kyoko's lie and was sentenced, but Alter Ego interrupted the execution and dropped him into the refuse pit. Kyoko rescued him, and the survivors chose to confront the school's hidden truth in a final Trial."},
      {pretrial:"The survivors searched every remaining room and combined records about Hope's Peak, the sealed year they could not remember, Mukuro Ikusaba, and the worldwide Tragedy. Evidence showed that the group had once lived at the school voluntarily and that the mastermind had manipulated both their memories and the earlier crime scenes.",full:"The mastermind was revealed as the real Junko Enoshima, with Mukuro having posed as Junko before being killed. Junko explained the Tragedy, the stolen memories, and the killing game's broadcast to the ruined outside world. Makoto restored the survivors' hope, Junko accepted her own punishment, and the remaining students opened the school to face an uncertain future."}
    ],
    dr2:[
      {pretrial:"The class arrived on Jabberwock Island under Monomi's peaceful school-trip rules before Monokuma seized control and restored the killing game. Byakuya organized a tightly controlled party to prevent violence, but a blackout struck and he was found beneath a table, killed with a skewer despite the security measures.",full:"Nagito had arranged the blackout and planted a weapon in an attempt to provoke a murder, but Byakuya intervened. Teruteru, believing he was stopping Nagito, attacked through the floor and killed Byakuya instead. The class exposed Teruteru's location and alibi tricks; he was executed after revealing that fear for his mother helped drive him."},
      {pretrial:"Monokuma introduced the arcade game Twilight Syndrome Murder Case, which mirrored secrets from the students' past. Mahiru was then found dead at the beach house, where blocked entrances, wet evidence, and a concealed escape route tied the real crime to the game's story and to Fuyuhiko's anger.",full:"Peko killed Mahiru while trying to act on Fuyuhiko's behalf, then posed as the serial killer Sparkling Justice to obscure their relationship. Her claim that she was merely Fuyuhiko's tool failed to save him from responsibility or her from punishment. Peko died protecting Fuyuhiko during her execution, leaving him badly injured."},
      {pretrial:"A Despair Disease outbreak changed several students' behavior and isolated them in the hospital under Mikan's care. Ibuki was found apparently hanged in the music venue, followed by Hiyoko's concealed body. A falsified live video, altered venue, and rushed announcements hid the time and order of the two murders.",full:"Mikan used the disease and her access to the hospital to murder Ibuki, killed Hiyoko when she became an unexpected witness, and fabricated the venue broadcast. During the Trial her behavior changed as she spoke of a beloved person and recovered memories no one else possessed. She was convicted and executed, leaving the group with unsettling questions about their past."},
      {pretrial:"The survivors were trapped in the Funhouse without food until a murder occurred. Nekomaru, rebuilt as a robot, was found broken near the tower while strange elevators, clocks, and the building's apparent layout contradicted one another. Solving the Funhouse's true structure became necessary to explain the impossible scene.",full:"Gundham and Nekomaru had agreed to a deadly duel rather than let everyone starve. Gundham used the building's vertical structure, a timed alarm, and Nekomaru's sleep function to create the apparent locked-room murder. He defended the value of struggling to live before accepting his execution, and the survivors finally escaped the Funhouse."},
      {pretrial:"Nagito discovered information in the Final Dead Room and began treating the group with open contempt. He threatened to destroy the island with planted bombs, then arranged a warehouse fire where his brutally injured body was found. Every survivor appeared to have participated in extinguishing the fire, making the killer impossible to isolate by ordinary means.",full:"Nagito had engineered his own death so that only the hidden traitor would unknowingly throw the fatal fire grenade, trusting his luck to select that person. The traitor was Chiaki, an observer created to protect the group, and Monomi shared her fate. Their execution removed the group's guide while revealing how completely Nagito had weaponized both truth and chance."},
      {pretrial:"The island began to glitch as the survivors entered the ruined Hope's Peak environment and uncovered records connecting themselves to the Remnants of Despair. Hajime learned about the Izuru Kamukura project, while evidence showed that the island, their bodies, and even their memories did not match the reality they believed they knew.",full:"Jabberwock Island was a virtual rehabilitation program, and the students had entered it as the Remnants of Despair. An artificial Junko tried to force a shutdown that would overwrite the survivors with their dead classmates and spread her influence outside. Hajime rejected both predetermined choices, the class created its own future, and the surviving students woke in the real world determined to help everyone left behind."}
    ],
    v3:[
      {pretrial:"Sixteen students awoke inside the Ultimate Academy and received talents and memories through Flashback Lights. Monokuma imposed a time limit for the first murder. Kaede and Shuichi set a trap in the library to expose the hidden mastermind, but Rantaro was found dead there when the countdown ended.",full:"The Trial concluded that Kaede's shot-put-ball trap had killed Rantaro while she was trying to stop the mastermind. She encouraged Shuichi to face the truth even when it condemned her, then was executed. Shuichi removed his hat and chose to carry her resolve forward as the academy opened new areas."},
      {pretrial:"Motive videos suggested that each student had someone waiting outside. Ryoma, who struggled to find a reason to live, was later discovered in the piranha tank during Himiko's underwater escape show. The gym's sealed schedule, a ropeway between windows, and the movement of the body connected the murder to the night before.",full:"Kirumi had drowned Ryoma and transported his body to create the magic-show discovery. Her motive video claimed she was the de facto prime minister responsible for an entire nation, and she had chosen that duty over the class. The group rejected her escape attempt, and she was executed after one final desperate climb."},
      {pretrial:"Angie formed a student council and tried to prevent the killing game through strict rules and a resurrection ritual. She was found dead in her locked research lab, and Tenko later died during Korekiyo's seance. The two different rooms, a spinning floorboard, and a loosened cage suggested that the murders were linked but not identical.",full:"Korekiyo had killed both Angie and Tenko, using the empty room's floorboard as a seesaw mechanism during the seance. He described the murders as gifts for the spirit of his sister and admitted to a long pattern of killing. The class convicted him, and Monokuma carried out an execution that continued even after his apparent death."},
      {pretrial:"Miu brought everyone into a Virtual World where she had secretly altered the rules and planned to kill Kokichi. Instead, her real body died while connected. The investigation had to translate avatars, objects, loading points, and a world whose opposite edges were connected into the physical actions behind the crime.",full:"Kokichi had discovered Miu's plan and manipulated Gonta into killing her inside the simulation. A memory error left Gonta unable to remember what he had done, but the program's rules and Kokichi's account proved it. Gonta accepted the verdict and was executed, after which Kokichi claimed to be the killing game's mastermind and openly took control of the remaining Exisals."},
      {pretrial:"Kokichi held Kaito in the hangar while Maki tried to rescue him with a poisoned crossbow. Later, a hydraulic press crushed an unidentified victim and an Exisal concealed the survivor, creating a case designed so that even Monokuma could not know whether Kaito or Kokichi had died.",full:"Kokichi was the victim and Kaito the killer, cooperating on an unsolvable murder intended to break the killing game. Video, clothing, and Kaito's failing health finally exposed the switch. Kaito accepted the verdict and began his space-themed execution, but died from illness before Monokuma could complete it, denying the headmaster a clean victory."},
      {pretrial:"With the academy damaged and Keebo openly resisting Monokuma, Shuichi used the final investigation to connect the hidden passage, Rantaro's survivor message, the audience, the Flashback Lights, and inconsistencies in the first murder. The remaining students entered a final Trial to challenge the entire story of the academy.",full:"Tsumugi revealed herself as the mastermind and claimed the students, their talents, and the outside world were elements of a long-running fictional Danganronpa series. Evidence also showed that Kaede had been framed for Rantaro's murder. Shuichi refused both hope and despair, convincing the audience to stop participating; Keebo destroyed the academy, and Shuichi, Maki, and Himiko emerged to search for whatever truth existed beyond it."}
    ]
  };

  const animeRecaps=[
    "Makoto was brought before the Future Foundation leaders to answer for protecting the Remnants of Despair. Before the dispute could be resolved, Monokuma sealed the building, fitted everyone with forbidden-action bracelets, and announced a new killing game. When the first sleep period ended, Chisa Yukizome was found dead.",
    "Years earlier, Chisa became assistant homeroom teacher for Hope's Peak's Class 77-B. She chased down her frequently absent students, brought them together through a chaotic class activity, and began forming the warm classroom community that she hoped to protect.",
    "The Future Foundation members learned that an attacker would kill during each sleep period and that breaking a personal forbidden action meant instant death. Daisaku Bandai died after triggering his bracelet, alliances fractured, and Makoto tried to persuade the others to cooperate before the next time limit.",
    "Chisa continued repairing relationships inside Class 77-B, with Mahiru's photos and a class party helping the students feel like a group. Hajime, watching from the Reserve Course, grew closer to Chiaki while remaining painfully aware that he lacked an Ultimate talent.",
    "Ruruka, Izayoi, and Seiko's old grievances resurfaced while Munakata's faction pursued Makoto. Great Gozu protected Makoto and Aoi, but the next sleep period ended with Gozu dead, proving that the hidden attacker remained active.",
    "Hajime met Natsumi Kuzuryu in the Reserve Course and learned how desperately she wanted recognition from the Main Course. Her sudden death and Sato's involvement pulled Mahiru and Fuyuhiko into the aftermath, while Hajime's frustration with Hope's Peak pushed him toward the academy's talent project.",
    "Seiko used performance-enhancing medicine to battle Ruruka and Izayoi as their broken friendship turned violent. Kyoko investigated the bodies and the bracelets, while Makoto's group kept moving through the facility and the survivors became increasingly willing to treat one another as enemies.",
    "Class 77-B faced a practical exam that became an elaborate confrontation with Nagito's luck, Seiko's medicine, and Ruruka's explosives. The resulting damage separated Chisa from her class, and the academy reassigned her to supervise the increasingly angry Reserve Course.",
    "Seiko survived Ruruka's trap but was killed during the next attacker period. Ruruka manipulated Izayoi through her sweets and ultimately killed him when she feared his forbidden action would expose an exit. Kyoko continued collecting evidence while the number of possible allies shrank.",
    "After six months away, Chisa returned to Class 77-B and found that relationships had changed. Chiaki had become the class representative who held everyone together, while Hajime had disappeared into the Kamukura Project and emerged as the talent-filled Izuru Kamukura.",
    "The Future Foundation launched an assault against Munakata's group as both sides blamed the other for the killing game. Juzo hunted the remaining participants, Tengan challenged Munakata directly, and Tengan's final words suggested that the game hid a deeper purpose.",
    "Junko Enoshima and Mukuro Ikusaba arrived at Hope's Peak and began preparing the despair that would consume the academy. Ryota's animation techniques caught Junko's attention, and Chisa started investigating the institution's secret project while Hajime's former self seemed increasingly distant.",
    "The story moved to Towa City, where Komaru and Toko confronted Monaca. Monaca described an attempt to create a new Junko, but Komaru rejected her manipulation, and Monaca abandoned the plan before leaving Earth in an absurd final gesture.",
    "Junko used Ryota's animation knowledge to refine video capable of overwhelming viewers emotionally. The Student Council was forced into a mutual killing game, Izuru watched without intervening, and footage of the massacre became fuel for unrest across the Reserve Course.",
    "Kyoko assembled the survivors for a murder reconstruction and exposed Ruruka's role in Izayoi's death. Before the group could regain control, another sleep period struck; Ruruka died, and Kyoko appeared to succumb to her own bracelet when Makoto remained alive past its deadline.",
    "Nagito returned from suspension and encountered Izuru as chaos spread through the academy. Class 77-B tried to rescue Mikan and their missing teacher, but Junko's forces intercepted them and the class walked deeper into a carefully prepared trap.",
    "Makoto grieved for Kyoko while the facility's flooding made escape increasingly urgent. A hidden message and the pattern of deaths pointed toward secrets in the building itself, and Munakata—shaken by betrayal and loss—continued to see Makoto's faith in others as dangerous weakness.",
    "Chisa was captured and subjected to Junko's despair video and invasive conditioning. When Class 77-B found her, the teacher they trusted led them onward while secretly serving Junko, and Chiaki was separated from the others to become the center of the next demonstration.",
    "Makoto confronted Munakata and used Kyosuke's forbidden action to force a conversation rather than another duel. The two finally compared what they knew, and Munakata began to understand that eliminating everyone associated with despair could not reveal the attacker or honor the people he had lost.",
    "Chiaki was forced through a deadly maze while her classmates watched through Junko's video. Her suffering and death broke Class 77-B and completed their conversion into the Remnants of Despair, while Izuru shed a tear he could not explain.",
    "Evidence showed there was no roaming attacker: each victim had been manipulated by a despair video into taking their own life during the sleep period. Makoto tested the discovery on himself but was saved, and Ryota revealed that Tengan had pushed events toward a plan involving his animation technology.",
    "Hope's Peak collapsed into the Tragedy as the Reserve Course revolted and Junko's influence spread worldwide. Chisa concealed her despair from Munakata, the surviving Class 78 students sealed themselves inside the school, and the members of Class 77-B departed as Junko's Remnants of Despair.",
    "The survivors escaped the collapsing facility while Ryota began broadcasting a Hope Video intended to overwrite humanity's emotions. Mitarai believed forced hope would end despair permanently, but Makoto rejected a peace created by removing everyone's ability to choose.",
    "The rehabilitated Class 77-B students arrived to stop Ryota's broadcast and accepted public blame so the Future Foundation could rebuild. Kyoko was revived through Seiko's antidote, Makoto prepared to reopen Hope's Peak, and the survivors moved forward with hope based on choice rather than control."
  ];

  window.CAST_MONOPAD_DATA={version:2,profileImages,profileOverrides,bios,recaps,animeRecaps};
})();
